name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.6.0
        with:
          distribution: temurin
          java-version: 21
      # required for dmn-to-image tests
      - uses: nanasess/setup-chromedriver@v2
      - uses: sbt/setup-sbt@v1
      - name: Build and Test
        run: sbt test
      - name: scalafmt check
        run: sbt scalafmtCheckAll
      - name: Check for uncommitted changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "There are uncommitted changes in the working directory:"
            git status --porcelain
            exit 1
          fi
        shell: bash